### ISSUE TITLE
我用的是小狼毫绿色便携版，WeaselServer.exe路径并不是固定的。

### ISSUE THREAD

**Issue by fudilove** [rockbenben/rime-WeaselServer#4]
或许我的路径是D:\srf下
并不是在安装版默认路径下。

**Comment by fudilove** [comment]
你这个限死了路径不是个好办法，那假设明天出新版，0.16呢
对绿色版你这个就无效

**Comment by fudilove** [comment]
你可以让用户设定路径，或可放在同一文件夹自动识别当前路径

**Comment by rockbenben** [comment]
> 你可以让用户设定路径，或可放在同一文件夹自动识别当前路径

0.03 版本中采用了这个逻辑，但是 Rime 每隔几年才更新一次。为了简化操作，我在 0.04 中将路径固定了。

你提到的绿色版问题我之前没有考虑到。刚更新的 0.05 版本解决了这问题，会兼容绿色版本。脚本会检测同目录下是否存在小狼毫算法程序，如果不存在，才会使用 0.15.0 的默认安装路径。
