### ISSUE TITLE
系统任务栏状态栏图表能否设置隐藏

### ISSUE THREAD

**Issue by nortant** [rockbenben/rime-WeaselServer#5]
非常感谢这个程序能够解决这个长期困扰我的问题，使用过程中确实很好，没有任何问题。

这个每次启动后任务栏的小火箭图标不知能否隐藏。

不过问这个问题的时候我自己也想了一下也有点多余…因为如果要设计隐藏，就有人还会想把他放出来，因为可以通过任务栏图标状态判断执行情况，可能就会让这个程序越来越复杂…

看情况吧，这不算是一个必须的需求。

**Comment by rockbenben** [comment]
添加参数 #NoTrayIcon 即可隐藏图标。

一般不用添加。开机五分钟内，脚本会自动退出，图标也会消失。

**Comment by nortant** [comment]
感谢回复。

只有20年前学过一点C语言基础的我，硬着头皮看了几个教学视频，最终搞定了～
